"""Scan ALL sent emails for SAR requests generated by this project,
populate user_data/sent_letters.json, run the monitor, and start the dashboard.

Usage:
    python import_sent_sars.py --account traderm1620@gmail.com
    python import_sent_sars.py --account traderm1620@gmail.com --no-dashboard
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from email.utils import parsedate_to_datetime
from pathlib import Path

from auth.gmail_oauth import get_gmail_service
from config.settings import get_settings

_TRACKER_PATH = Path(__file__).parent / "user_data" / "sent_letters.json"


# ---------------------------------------------------------------------------
# Gmail helpers
# ---------------------------------------------------------------------------

def _all_sent_sars(service, subject_prefix: str) -> list[dict]:
    """Page through Gmail Sent and return every message whose subject starts
    with the SAR prefix generated by this project."""
    query = f'subject:"{subject_prefix}" in:sent'
    print(f"Gmail query: {query}")

    messages = []
    page_token = None
    page = 0

    while True:
        page += 1
        kwargs: dict = {"userId": "me", "q": query, "maxResults": 500}
        if page_token:
            kwargs["pageToken"] = page_token

        result = service.users().messages().list(**kwargs).execute()
        batch = result.get("messages", [])
        messages.extend(batch)
        print(f"  Page {page}: {len(batch)} message(s) (total so far: {len(messages)})")

        page_token = result.get("nextPageToken")
        if not page_token:
            break

    return messages


def _get_detail(service, msg_id: str) -> dict | None:
    try:
        # Request all metadata headers (no filter) so we don't miss anything
        return service.users().messages().get(
            userId="me",
            id=msg_id,
            format="metadata",
        ).execute()
    except Exception as e:
        print(f"  Warning: could not fetch {msg_id}: {e}")
        return None


def _parse_date(date_str: str) -> str:
    try:
        dt = parsedate_to_datetime(date_str)
        return dt.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")
    except Exception:
        return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")


def _guess_company(to_addr: str) -> str:
    try:
        domain = to_addr.split("@")[-1].rstrip(">").strip()
        parts = domain.split(".")
        if len(parts) >= 3 and parts[-2] in ("co", "com", "org", "net"):
            name = parts[-3]
        elif len(parts) >= 2:
            name = parts[-2]
        else:
            name = domain
        return name.capitalize()
    except Exception:
        return to_addr


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    args = _parse_args()

    if not Path("credentials.json").exists():
        print("credentials.json not found. Run python setup.py first.")
        sys.exit(1)

    settings = get_settings()
    subject_prefix = f"Subject Access Request — {settings.user_full_name}"

    print(f"Connecting to Gmail as {args.account or '(auto)'}...")
    service, email = get_gmail_service(email_hint=args.account)
    print(f"Connected: {email}")
    print(f"Looking for subject prefix: '{subject_prefix}'\n")

    # Fetch all matching sent messages
    raw_messages = _all_sent_sars(service, subject_prefix)
    print(f"\nFound {len(raw_messages)} SAR email(s) in Sent folder.\n")

    if not raw_messages:
        print("Nothing found. Check that you're connected to the right Gmail account.")
        sys.exit(0)

    # Load existing valid entries (those with real thread IDs)
    if _TRACKER_PATH.exists():
        try:
            existing_all = json.loads(_TRACKER_PATH.read_text())
        except Exception:
            existing_all = []
    else:
        existing_all = []

    existing_valid = [r for r in existing_all if r.get("gmail_thread_id") and r.get("to_email")]
    existing_msg_ids = {r["gmail_message_id"] for r in existing_valid}

    dropped = len(existing_all) - len(existing_valid)
    if dropped:
        print(f"Discarding {dropped} existing entries with missing thread IDs.\n")

    # Resolve each found message into a tracker entry
    new_entries = []
    already_tracked = 0

    for m in raw_messages:
        if m["id"] in existing_msg_ids:
            already_tracked += 1
            continue

        detail = _get_detail(service, m["id"])
        if not detail:
            continue

        headers = {h["name"].lower(): h["value"] for h in detail["payload"]["headers"]}
        to_addr = headers.get("to", "")
        subject = headers.get("subject", "")
        date_str = headers.get("date", "")

        entry = {
            "sent_at":           _parse_date(date_str),
            "company_name":      _guess_company(to_addr),
            "method":            "email",
            "to_email":          to_addr,
            "subject":           subject,
            "gmail_message_id":  m["id"],
            "gmail_thread_id":   detail["threadId"],
        }
        new_entries.append(entry)
        print(f"  + {entry['sent_at']}  {entry['company_name']:<25}  {to_addr}")

    print(f"\nSummary:")
    print(f"  Already tracked : {already_tracked}")
    print(f"  New recovered   : {len(new_entries)}")

    if not new_entries and not existing_valid:
        print("\nNo SAR records to save.")
        sys.exit(0)

    merged = existing_valid + new_entries
    _TRACKER_PATH.parent.mkdir(parents=True, exist_ok=True)
    _TRACKER_PATH.write_text(json.dumps(merged, indent=2))
    print(f"  Total in tracker: {len(merged)}")
    print(f"\nSaved to {_TRACKER_PATH}")

    if args.no_dashboard:
        print("\nDone. Run 'python monitor.py' to refresh, or 'python dashboard/app.py' for the web UI.")
        return

    # Sync reply states
    print("\nFetching reply states from Gmail...")
    subprocess.run([sys.executable, "monitor.py", "--account", email], check=False)

    # Launch dashboard
    print("\n" + "=" * 50)
    print("  Dashboard → http://localhost:5001")
    print("  Press Ctrl+C to stop.")
    print("=" * 50 + "\n")
    subprocess.run([sys.executable, "dashboard/app.py"])


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Import all sent SARs from Gmail and launch dashboard")
    p.add_argument("--account", metavar="EMAIL", default=None)
    p.add_argument("--no-dashboard", action="store_true")
    return p.parse_args()


if __name__ == "__main__":
    main()
